# Use the base image
FROM taoufikel/ml-energy-cpu

# Install missing dependencies
RUN pip install imbalanced-learn

# Set the working directory
WORKDIR /workspace

# Copy your code into the container
COPY nn.py /workspace/
COPY Dataset /workspace/Dataset/

# Run nn.py when the container starts
CMD ["/workspace/nn.py"]